### ISSUE TITLE
Archive?

### ISSUE THREAD

**Issue by mcclowes** [Codogo/Knowt-Document#1]
@FreddieRidell I assume there's no reason we can't archive this?
Similarly, I think there was an associated NPM package?

**Comment by FreddieRidell** [comment]
*sigh*, yeah, probably
npm's not really a concern, the package removal process is quite a ballache

**Comment by mcclowes** [comment]
-I think they've made it easier actually-
Nah actually it was just the last repo I unpublished met certain criteria

**Comment by mcclowes** [comment]
Have deprecated the package
